# Generated by Django 2.2.3 on 2019-07-31 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('content', models.TextField()),
                ('users', models.ManyToManyField(related_name='course_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
